# This file was generated by GoReleaser. DO NOT EDIT.
cask "nota" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "b757c0bbac15b3320481eb1f3a51fb232d050bf1af60275936fd7419c5a37c55"
      url "https://github.com/ariedotme/nota/releases/download/v#{version}/nota_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d411016d46914b0fe2073f92b9e2cecf2aab81a859f507274806c7b465e46a5"
      url "https://github.com/ariedotme/nota/releases/download/v#{version}/nota_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "20efac7343aeba1a7940a324ba7edbc91fb34b4a0df8159e1718bd00ed73a0db"
      url "https://github.com/ariedotme/nota/releases/download/v#{version}/nota_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "10afb42455dd907b978b43fd3b79654a687abf6b447c625df9de273f1218c6c6"
      url "https://github.com/ariedotme/nota/releases/download/v#{version}/nota_linux_arm64.tar.gz"
    end
  end

  name "nota"
  desc "Notes, journal, and tasks in plain Markdown, from the terminal"
  homepage "https://github.com/ariedotme/nota"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nota"
  manpage "man/nota.1"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nota"]
    end
  end
  generate_completions_from_executable "nota", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
