# This file was generated by GoReleaser. DO NOT EDIT.
cask "nota" do
  version "0.1.10"

  on_macos do
    on_intel do
      sha256 "541bec8f4f722f65e70d7bd9d85fa7c20ba5cb98163c7a6ecde95e63befc06c4"
      url "https://github.com/ariedotme/nota/releases/download/v#{version}/nota_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cd7f2eb9ffa2efd9c0ea8df2e0496d2246e653b3abfef3f12c9abbcd21358d08"
      url "https://github.com/ariedotme/nota/releases/download/v#{version}/nota_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4eb9f19cd3275c3cdfeb185884bc8e833925104406cfaf39c2253aef6282a072"
      url "https://github.com/ariedotme/nota/releases/download/v#{version}/nota_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "37687388f958c3ee13a140b18c34cd6a4230206ee87fcdb5f8250f983d5f7281"
      url "https://github.com/ariedotme/nota/releases/download/v#{version}/nota_linux_arm64.tar.gz"
    end
  end

  name "nota"
  desc "Notes, journal, and tasks in plain Markdown, from the terminal"
  homepage "https://github.com/ariedotme/nota"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nota"
  manpage "man/nota.1"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nota"]
    end
  end
  generate_completions_from_executable "nota", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
