# This file was generated by GoReleaser. DO NOT EDIT.
cask "nota" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "8f4fe830a55b1239f600238e0fbb72ef66a45c9664bc10872003671baf6d5e99"
      url "https://github.com/ariedotme/nota/releases/download/v#{version}/nota_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "22b30221ba8781c29e86f5aa103522971a93205dcc22817f120cc0a348aae6f8"
      url "https://github.com/ariedotme/nota/releases/download/v#{version}/nota_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "47ce01ef4f465effa6c787de0ce9b71637909cf4b21aa05ed868b8e750656414"
      url "https://github.com/ariedotme/nota/releases/download/v#{version}/nota_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8c15b657278a03d9cdb5285d7d39cb9c69620d0690282d7905cc07ec3c1421d9"
      url "https://github.com/ariedotme/nota/releases/download/v#{version}/nota_linux_arm64.tar.gz"
    end
  end

  name "nota"
  desc "Notes, journal, and tasks in plain Markdown, from the terminal"
  homepage "https://github.com/ariedotme/nota"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nota"
  manpage "man/nota.1"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nota"]
    end
  end
  generate_completions_from_executable "nota", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
