# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nota < Formula
  desc "Notes, journal, and tasks in plain Markdown, from the terminal"
  homepage "https://github.com/ariedotme/nota"
  version "0.1.0"
  license "MIT"

  depends_on "fzf" => :optional
  depends_on "ripgrep" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ariedotme/nota/releases/download/v0.1.0/nota_darwin_amd64.tar.gz"
      sha256 "49599a549c19cdc42a2d4adceac854787347316b5ab6316b6dd053a4b641901f"

      define_method(:install) do
        bin.install "nota"
        generate_completions_from_executable(bin/"nota", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ariedotme/nota/releases/download/v0.1.0/nota_darwin_arm64.tar.gz"
      sha256 "6dcbb0965d2fa022cac43ab4c5e9395f81ab32b3d48238c821e26cc67cda452c"

      define_method(:install) do
        bin.install "nota"
        generate_completions_from_executable(bin/"nota", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ariedotme/nota/releases/download/v0.1.0/nota_linux_amd64.tar.gz"
      sha256 "b18fc9efc575c30b48604455cbb734be9863d85b6416291230753f8e1c20f55a"
      define_method(:install) do
        bin.install "nota"
        generate_completions_from_executable(bin/"nota", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ariedotme/nota/releases/download/v0.1.0/nota_linux_arm64.tar.gz"
      sha256 "2445a2da0c25e47ec805e14da2a2470858fe79475155cf4c4da28ec230caa0c3"
      define_method(:install) do
        bin.install "nota"
        generate_completions_from_executable(bin/"nota", "completion")
      end
    end
  end

  test do
    system "#{bin}/nota", "--version"
  end
end
